<?php
    $this->headScript()->appendFile($this->assetUrl('jquery-ui.min.js', 'jQueryUI'));
    $this->headLink()->appendStylesheet($this->assetUrl('jquery-ui.min.css', 'jQueryUI'));
    $this->headScript()->appendFile($this->assetUrl('js/psl-tabs.js', 'PslSearchForm'));
    $this->headLink()->appendStylesheet($this->assetUrl('css/psl-form.css', 'PslSearchForm'));
?>

<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>

<div id="psl-search-form-wrapper">
    <button type="button" class="psl-new-search"><?php echo $this->translate('New search'); ?></button>
    <div id="psl-search-form">
        <ul class="psl-tabs">
            <li class="psl-tab-map">
                <a href="#psl-search-form-map" title="<?php echo $this->translate('Location'); ?>"><i class="fa fa-map-marker"></i></a>
            </li>
            <li class="psl-tab-date">
                <a href="#psl-search-form-date" title="<?php echo $this->translate('Time period'); ?>"><i class="fa fa-hourglass-half"></i></a>
            </li>
            <li class="psl-tab-itemset">
                <a href="#psl-search-form-itemset" title="<?php echo $this->translate('Collections'); ?>"><i class="fa fa-book"></i></a>
            </li>
            <li class="psl-tab-search">
                <button type="button" class="reset-tab" data-tab="search"><i class="fa fa-times-circle-o"></i></button>
                <?php echo $this->formText($form->get('q')); ?>
            </li>
            <li class="psl-tab-text">
                <a href="#psl-search-form-text" title="<?php echo $this->translate('More'); ?>"><i class="fa fa-plus"></i></a>
            </li>
            <li class="psl-tab-submit"><input type="submit" value="OK"/></li>
        </ul>
        <div id="psl-search-form-map">
            <?php echo $this->formCollection($form->get('map'), false); ?>
            <button type="button" class="reset-tab" data-tab="map"><?php echo $this->translate('Reset'); ?></button>
        </div>
        <div id="psl-search-form-date">
            <label><?php echo $this->translate('Time period'); ?></label>
            <?php echo $this->formCollection($form->get('date'), false); ?>
            <div id="psl-search-form-date-slider"></div>
            <div id="psl-search-form-date-graduations">
                <div><?php echo $this->translate('14th century'); ?></div>
                <div><?php echo $this->translate('15th'); ?></div>
                <div><?php echo $this->translate('16th'); ?></div>
                <div><?php echo $this->translate('17th'); ?></div>
                <div><?php echo $this->translate('18th'); ?></div>
                <div><?php echo $this->translate('19th'); ?></div>
                <div><?php echo $this->translate('20th'); ?></div>
                <div><?php echo $this->translate('21th century'); ?></div>
            </div>
            <button type="button" class="reset-tab" data-tab="date"><?php echo $this->translate('Reset'); ?></button>
        </div>
        <div id="psl-search-form-itemset">
            <?php echo $this->formCollection($form->get('itemSet'), false); ?>
            <button type="button" class="reset-tab" data-tab="itemset"><?php echo $this->translate('Reset'); ?></button>
        </div>
        <div id="psl-search-form-text">
            <?php echo $this->formCollection($form->get('text'), false); ?>
            <button type="button" class="reset-tab" data-tab="text"><?php echo $this->translate('Reset'); ?></button>
        </div>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>

<script>
    $(document).ready(function() {
        $('#psl-search-form').pslTabs();

        var dateInputs = $('#psl-search-form-date input');
        var itemsetInputs = $('#psl-search-form-itemset input');
        var searchInputs = $('#psl-search-form .psl-tab-search input');

        var tabs = {
            date: {
                inputs: dateInputs,
                isPopulated: function() {
                    var inputs = dateInputs.toArray();
                    for (var i = 0; i < inputs.length; i++) {
                        if (inputs[i].value !== '') {
                            return true;
                        }
                    }
                },
                reset: function() {
                    var dateSlider = $('#psl-search-form-date-slider');
                    var min = dateSlider.slider('option', 'min');
                    var max = dateSlider.slider('option', 'max');
                    dateSlider.slider('values', [min, max]);
                }
            },
            itemset: {
                inputs: itemsetInputs,
                isPopulated: function() {
                    var inputs = itemsetInputs.toArray();
                    for (var i = 0; i < inputs.length; i++) {
                        if (inputs[i].checked) {
                            return true;
                        }
                    }
                },
                reset: function() {
                    itemsetInputs.prop('checked', false).change();
                }
            },
            search: {
                inputs: searchInputs,
                isPopulated: function() {
                    var inputs = searchInputs.toArray();
                    for (var i = 0; i < inputs.length; i++) {
                        if (inputs[i].value !== '') {
                            return true;
                        }
                    }
                },
                reset: function() {
                    searchInputs.val('').change();
                }
            }
        };

        var formIsPopulated = function() {
            return $('#psl-search-form .psl-tab-populated').length > 0;
        };

        // Populated tab markers
        for (name in tabs) {
            var tab = tabs[name];
            var handler = (function(name) {
                return function() {
                    var li = $('#psl-search-form li.psl-tab-' + name);
                    var div = $('#psl-search-form-' + name);
                    if (tabs[name].isPopulated()) {
                        li.addClass('psl-tab-populated');
                        div.addClass('psl-tab-populated');
                    } else {
                        li.removeClass('psl-tab-populated');
                        div.removeClass('psl-tab-populated');
                    }

                    var newSearchButton = $('#psl-search-form-wrapper .psl-new-search');
                    if (formIsPopulated()) {
                        newSearchButton.css('visibility', 'visible');
                    } else {
                        newSearchButton.css('visibility', 'hidden');
                    }
                };
            })(name);
            tab.inputs.on('change keyup', handler).trigger('change');
        }

        // Reset buttons
        $('#psl-search-form button.reset-tab').on('click', function(e) {
            e.preventDefault();
            var name = $(this).attr('data-tab');
            tabs[name].reset();
        });

        $('#psl-search-form-wrapper .psl-new-search').on('click', function(e) {
            e.preventDefault();
            for (name in tabs) {
                tabs[name].reset();
            }
        });
    });

    $(document).ready(function() {
        var dateFrom = $('#psl-search-form input[name="date[from]"]');
        var dateTo = $('#psl-search-form input[name="date[to]"]');
        var dateMin = 1300;
        var dateMax = 2100;

        $('#psl-search-form-date-slider').slider({
            range: true,
            min: dateMin,
            max: dateMax,
            step: 100,
            values: [dateFrom.val() || dateMin, dateTo.val() || dateMax],
            change: function(event, ui) {
                var from = ui.values[0] > dateMin ? ui.values[0] : '';
                var to = ui.values[1] < dateMax ? ui.values[1] : '';
                if (from != dateFrom.val()) {
                    dateFrom.val(from).change();
                }
                if (to != dateTo.val()) {
                    dateTo.val(to).change();
                }
            }
        });

        dateFrom.parents('.field').hide();
        dateTo.parents('.field').hide();
    });
</script>
