<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */

$this->headLink()->appendStylesheet($this->assetUrl('jquery-ui.min.css', 'jQueryUI'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet/leaflet.css', 'PslSearchForm'));
$this->headLink()->appendStylesheet($this->assetUrl('css/psl-search-form.css', 'PslSearchForm'));

// Js are prepended to avoid issues with module Mapping, that uses leaflet too..
$this->headScript()->prependFile($this->assetUrl('js/psl-search-form.js', 'PslSearchForm'));
$this->headScript()->prependFile($this->assetUrl('vendor/leaflet/leaflet.js', 'PslSearchForm'));
$this->headScript()->prependFile($this->assetUrl('jquery-ui.min.js', 'jQueryUI'));
